// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDayBlock(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddDayBlock'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddWeekTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddWeekTask'](arg1, arg2, arg3);
}

export function GetAlwaysOnTop() {
  return window['go']['main']['App']['GetAlwaysOnTop']();
}

export function GetDayBlocks(arg1) {
  return window['go']['main']['App']['GetDayBlocks'](arg1);
}

export function GetMonthGoals(arg1, arg2) {
  return window['go']['main']['App']['GetMonthGoals'](arg1, arg2);
}

export function GetWeekTasks(arg1, arg2) {
  return window['go']['main']['App']['GetWeekTasks'](arg1, arg2);
}

export function RemoveDayBlock(arg1) {
  return window['go']['main']['App']['RemoveDayBlock'](arg1);
}

export function RemoveWeekTask(arg1) {
  return window['go']['main']['App']['RemoveWeekTask'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetMonthGoals(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMonthGoals'](arg1, arg2, arg3);
}

export function ToggleWeekTask(arg1) {
  return window['go']['main']['App']['ToggleWeekTask'](arg1);
}

export function UpdateDayBlock(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateDayBlock'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
