// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDayBlock(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string,arg6:string):Promise<void>;

export function AddWeekTask(arg1:number,arg2:number,arg3:string):Promise<void>;

export function GetAlwaysOnTop():Promise<boolean>;

export function GetDayBlocks(arg1:string):Promise<Array<main.TimeBlock>>;

export function GetMonthGoals(arg1:number,arg2:number):Promise<Array<main.MonthGoal>>;

export function GetWeekTasks(arg1:number,arg2:number):Promise<Array<main.WeekTask>>;

export function RemoveDayBlock(arg1:string):Promise<void>;

export function RemoveWeekTask(arg1:string):Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetMonthGoals(arg1:number,arg2:number,arg3:Array<string>):Promise<void>;

export function ToggleWeekTask(arg1:string):Promise<void>;

export function UpdateDayBlock(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
